### ISSUE TITLE
Assimp Headers not found

### ISSUE THREAD

**Issue by joskuijpers** [ctreffs/SwiftAssimp#1]
Hey,

I cloned the project and tried to build it but it fails to find the header files. I installed assimp using brew, and it is even linked from /usr/local/include

There is this note about pkgConfig in the Package.swift but I am not sure what I need to do.

Can you help me out?

**Comment by joskuijpers** [comment]
I have renamed the .Mac.pc to .pc, and used `swift build` instead of Xcode. This gives me a bunch of files. Going to find out how to use that now. Directly using this package over GitHub in a project does not work because the of the include header issue.

**Comment by joskuijpers** [comment]
Okay... I am quite new to SPM, I used to do everything with Xcode. Apparently there is a huge difference between Xcode and CLI swift pm commands, because it now works fine using the command line... I was able to make an SPM package that uses this package.

Putting the working SPM app (with swift build) into an Xcode project gives me the cimport.h error again... great 😄

**Comment by ctreffs** [comment]
Hi @joskuijpers,

thanks for reaching out. 
There is currently a regression in the assimp library, introduced with version 5 that breaks the pkg-config file of the assimp library (wrong include directory).
I've raised the issue https://github.com/assimp/assimp/issues/3174 and hope for a fix from their end.

Until then the best way to get it working is to install via brew, as you did but, replace the pkg-config file with corrected content (see `assimp5.mac.pc` in this project).
The assimp pkg-config file can be found here `/usr/local/Cellar/assimp/5.0.1/lib/pkgconfig/assimp.pc`
depending on your assimp version (5.0.0 or 5.0.1 currently).

Depending on your assimp version you will have to adjust the pkg-config file 
i.e. for version 5.0.0 it looks like in `assimp5.mac.pc`,
for version 5.0.1 it should look like this: 

```sh
prefix=/usr/local/Cellar/assimp/5.0.1
exec_prefix=/usr/local/Cellar/assimp/5.0.1/
libdir=/usr/local/Cellar/assimp/5.0.1/lib
includedir=/usr/local/Cellar/assimp/5.0.1/include

Name: Assimp
Description: Import various well-known 3D model formats in an uniform manner.
Version: 5.0.1
Libs: -L${libdir} -lassimp
Libs.private:  -lz
Cflags: -I${includedir}
```

The pkg-config file tells SPM where to look for headers and libraries installed outside of the SPM project itself.

Sorry for the confusion here - but until this is fixed on assimps side we will have this problem, since you can't provide a custom pkg-config file in SPM for now, afaik.

Hope this helps :-)

**Comment by ctreffs** [comment]
Should be fixed with version https://github.com/ctreffs/SwiftAssimp/releases/tag/1.2.1

**Comment by joskuijpers** [comment]
I have done what you put in the updated readme but to no avail. Still the same error in Xcode. Restarted Xcode as well as cleaned the build directory.

I've no idea where to go from here using this method. I might try pulling all code of this project, the headers of Assimp and libAssimp.a into a project and see if that works.
